// packages/extension/entrypoints/options/components/Footer.tsx
import { Temporal } from "@js-temporal/polyfill";
import { Trans, useTranslation } from "react-i18next";

const generateYear = () => {
  const year = Temporal.Now.plainDateISO().year;
  return year === 2023 ? year : `2023-${year}`;
};

interface FooterLinkProps {
  href: string;
  content: string;
}

function FooterLink({ href, content }: FooterLinkProps) {
  return (
    <a
      className="font-semibold text-black underline decoration-solid transition hover:text-sky-500 dark:text-white"
      href={href}
      target="_blank"
      rel="noreferrer noopener"
    >
      {content}
    </a>
  );
}

export default function Footer() {
  const { t } = useTranslation();

  return (
    <footer className="border-gray-200 border-t dark:border-slate-800">
      <div className="mx-auto flex items-center justify-between px-4 sm:px-6 lg:px-8">
        <p className="flex flex-col flex-wrap gap-1.5 py-8 text-center text-sm sm:flex-row">
          <span className="block whitespace-nowrap sm:inline">
            <Trans
              i18nKey="footerCopyright"
              values={{ yearsRange: generateYear() }}
              components={{
                author: <FooterLink content="aiktb" href="https://github.com/aiktb" />,
              }}
            />
          </span>
          <span className="block sm:inline">
            <Trans
              i18nKey="footerLicense"
              components={{
                license: (
                  <FooterLink
                    content="MIT"
                    href="https://github.com/aiktb/FuriganaMaker/blob/main/LICENSE"
                  />
                ),
              }}
            />
          </span>
          <span className="block sm:inline">
            <Trans
              i18nKey="footerBuiltWith"
              components={{
                tool: <FooterLink content="WXT" href="https://wxt.dev" />,
              }}
            />
          </span>
        </p>
        <a
          className="flex size-9 items-center justify-center rounded-md text-black hover:bg-gray-100 dark:text-white dark:hover:bg-slate-800 dark:hover:text-white"
          href="https://github.com/aiktb/FuriganaMaker"
        >
          <span className="sr-only">{t("srGithub")}</span>
          <i className="i-fa6-brands-github size-5" />
        </a>
      </div>
    </footer>
  );
}

// src/options/components/Footer.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'

const generateYear = () => {
  const year = new Date().getFullYear()
  return year === 2023 ? year : `2023-${year}`
}
</script>

<template>
  <footer>
    <div
      class="mx-auto flex max-w-3xl items-center justify-between border-t border-gray-200 px-4 dark:border-slate-800 sm:px-6 lg:max-w-7xl lg:px-8"
    >
      <div class="py-8 text-center text-sm sm:text-left">
        <span class="block sm:inline"
          >Copyright &copy; {{ generateYear() }}
          <a
            class="text-sky-500 transition hover:text-sky-700"
            href="https://github.com/aiktb"
            target="_blank"
            >aiktb</a
          >.
        </span>
        <span class="block sm:inline"
          >Released under the
          <a
            class="text-sky-500 transition hover:text-sky-700"
            href="https://github.com/aiktb/FuriganaMaker/blob/main/LICENSE"
            target="_blank"
            >MIT</a
          >
          license.</span
        >
      </div>
      <a
        class="transition hover:text-black dark:hover:text-white"
        href="https://github.com/aiktb/FuriganaMaker"
        target="_blank"
      >
        <span class="sr-only">GitHub repository</span>
        <Icon class="h-6 w-6" icon="mdi:github" />
      </a>
    </div>
  </footer>
</template>
