// src/popup/components/Button.tsx
interface ButtonProps {
  text: string;
  onClick: () => void;
}

export default function Button({ text, onClick }: ButtonProps) {
  return (
    <button
      className="flex grow items-center justify-start gap-x-1 rounded px-2 capitalize transition-all hover:bg-gray-200 focus-visible:bg-gray-200 dark:hover:bg-slate-700 dark:focus-visible:bg-slate-700"
      onClick={onClick}
    >
      {text}
    </button>
  );
}

// src/popup/components/Button.vue
<script setup lang="ts"></script>

<template>
  <div class="button" tabindex="0" @keydown.enter="$emit('click')">
    <slot name="default" />
  </div>
</template>

<style scoped>
.button {
  display: flex;
  align-items: center;
  flex-grow: 1;
  box-sizing: border-box;
  height: 1.5rem;
  text-align: left;
  background-color: transparent;
  border: none;
  border-radius: 0.3rem;
  cursor: pointer;
  transition: all 250ms;
  padding: 0 0.5rem;
}

.button:hover,
.button:focus {
  background-color: var(--gray);
}
</style>
