// src/popup/components/CheckBox.tsx
import { Switch } from '@headlessui/react';

interface CheckBoxProps {
  checked: boolean;
  text: string;
  onChange: (checked: boolean) => void;
}

export default function CheckBox({ text, onChange, checked }: CheckBoxProps) {
  return (
    <Switch
      checked={checked}
      onChange={onChange}
      className="flex grow items-center justify-between rounded px-2"
    >
      {text}
    </Switch>
  );
}

// src/popup/components/CheckBox.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{ modelValue?: boolean }>()

const emit = defineEmits<{
  'update:modelValue': [modelValue: boolean]
  change: []
}>()

const root = ref<HTMLElement | null>(null)
defineExpose({
  focus: () => {
    root.value?.focus()
  }
})

const change = () => {
  emit('update:modelValue', !props.modelValue)
  emit('change')
}
</script>

<template>
  <button
    ref="root"
    role="checkbox"
    :aria-checked="props.modelValue"
    class="flex grow items-center justify-between rounded px-2"
    @click="change"
  >
    <slot name="default" />
  </button>
</template>
