// src/popup/components/ColorPicker.vue
<script setup lang="ts">
import { useElementBounding, useFocusWithin } from '@vueuse/core'
import tinycolor from 'tinycolor2'
import { computed, onMounted, ref, watch } from 'vue'

import { useDraggable } from '../composables/useDraggable'

const props = defineProps<{
  modelValue: string
}>()

const emit = defineEmits<{
  'update:modelValue': [modelValue: string]
  close: []
}>()

const update = (color: string) => {
  emit('update:modelValue', color)
  emit('close')
}

const panel = ref<HTMLElement | null>(null)
const { focused } = useFocusWithin(panel)
watch(focused, () => {
  if (!focused.value) {
    emit('close')
  }
})

// prettier-ignore
const colors = [
  'black', 'white', 'tomato', 'moccasin', 'orange',
  'yellow', 'lime', 'aqua', 'teal', 'fuchsia'
]

const hue = ref<HTMLCanvasElement | null>(null)
const hueCursor = ref<HTMLElement | null>(null)
const {
  left: hueLeft,
  top: hueTop,
  width: hueWidth,
  height: hueHeight
} = useElementBounding(hue)
const { x: hueX } = useDraggable(hueCursor, hue)
const hueBarStyle = computed(() => {
  return {
    left: `${hueX.value}px`,
    top: `${hueTop.value + hueHeight.value / 2}px`,
    backgroundColor: `hsl(${hsv.value.h}, 100%, 50%)`
  }
})

const shade = ref<HTMLCanvasElement | null>(null)
const shadeCursor = ref<HTMLElement | null>(null)
const {
  left: shadeLeft,
  top: shadeTop,
  width: shadeWidth,
  height: shadeHeight
} = useElementBounding(shade)
const { x: shadeX, y: shadeY } = useDraggable(shadeCursor, shade)
const shadeBarStyle = computed(() => {
  return {
    left: `${shadeX.value}px`,
    top: `${shadeY.value}px`,
    backgroundColor: tinycolor(hsv.value).toHslString()
  }
})

const hsv = computed(() => {
  const hue = ((hueX.value - hueLeft.value) / hueWidth.value) * 360
  const saturation = (shadeX.value - shadeLeft.value) / shadeWidth.value
  const value = 1 - (shadeY.value - shadeTop.value) / shadeHeight.value
  return { h: hue, s: saturation, v: value }
})

const input = ref(props.modelValue)

watch(hsv, (hsv) => {
  input.value = tinycolor(hsv).toHexString()
})

const colorToPosition = (color: string) => {
  if (tinycolor(color).isValid()) {
    const hsv = tinycolor(color).toHsv()
    hueX.value = hueWidth.value * (hsv.h / 360) + hueLeft.value
    shadeX.value = shadeWidth.value * hsv.s + shadeLeft.value
    shadeY.value = shadeHeight.value * (1 - hsv.v) + shadeTop.value
  } else if (color === 'currentColor') {
    hueX.value = hueLeft.value
    shadeX.value = shadeLeft.value
    shadeY.value = shadeTop.value
  }
}

onMounted(() => {
  const hueCanvas = hue.value!
  const hueCtx = hueCanvas.getContext('2d')!
  const hueGradient = hueCtx.createLinearGradient(0, 0, hueCanvas.width, 0)
  for (let percent = 0; percent <= 1; percent += 1 / 6) {
    hueGradient.addColorStop(percent, `hsl(${percent * 360}, 100%, 50%)`)
  }
  hueCtx.fillStyle = hueGradient
  hueCtx.fillRect(0, 0, hueCanvas.width, hueCanvas.height)
  const shadeCanvas = shade.value!
  const shadeCtx = shadeCanvas.getContext('2d')!
  // prettier-ignore
  const whiteGradient = shadeCtx.createLinearGradient(0, 0, shadeCanvas.width, 0)
  whiteGradient.addColorStop(0, '#ffffff')
  whiteGradient.addColorStop(1, 'transparent')
  // prettier-ignore
  const blackGradient = shadeCtx.createLinearGradient(0, 0, 0, shadeCanvas.height)
  blackGradient.addColorStop(0, 'transparent')
  blackGradient.addColorStop(1, '#000000')
  shadeCtx.fillStyle = whiteGradient
  shadeCtx.fillRect(0, 0, shadeCanvas.width, shadeCanvas.height)
  shadeCtx.fillStyle = blackGradient
  shadeCtx.fillRect(0, 0, shadeCanvas.width, shadeCanvas.height)

  colorToPosition(props.modelValue)
  panel.value?.focus()
})
</script>

<template>
  <div
    ref="panel"
    class="fixed bottom-0 left-0 right-0 top-0 z-10 flex flex-col items-center justify-between bg-slate-200 p-3 dark:bg-slate-800"
    tabindex="-1"
    aria-label="color picker"
  >
    <canvas
      id="shade"
      ref="shade"
      class="h-[70%] w-full rounded-sm"
      :style="{ backgroundColor: hueBarStyle.backgroundColor }"
    />
    <div
      id="shadeCursor"
      ref="shadeCursor"
      aria-label="shade cursor"
      class="fixed h-4 w-4 cursor-pointer rounded-full shadow-md transition-all duration-300 [transform:translate(-50%,-50%)] hover:transition-none focus:transition-none"
      tabindex="0"
      :style="shadeBarStyle"
      @keydown.up="shadeY--"
      @keydown.down="shadeY++"
      @keydown.left="shadeX--"
      @keydown.right="shadeX++"
      @keyup.enter="update(input)"
    />
    <canvas id="hue" ref="hue" class="h-[3%] w-full rounded" />
    <div
      id="hueCursor"
      ref="hueCursor"
      aria-label="hue cursor"
      class="fixed h-3 w-3 cursor-pointer rounded-full shadow-md transition-all duration-300 [transform:translate(-50%,-50%)] hover:transition-none focus:transition-none"
      tabindex="0"
      :style="hueBarStyle"
      @keydown.up="hueX--"
      @keydown.down="hueX++"
      @keydown.left="hueX--"
      @keydown.right="hueX++"
      @keyup.enter="update(input)"
    />
    <div class="flex w-full flex-wrap justify-between">
      <button
        v-for="color of colors"
        :key="color"
        class="border-1 h-3.5 w-3.5 rounded border-slate-700"
        :style="{ backgroundColor: color }"
        :class="{ 'border-none': tinycolor(color).toHexString() === input }"
        :aria-label="color"
        @click="colorToPosition(color)"
      />
    </div>
    <div class="grid w-full grid-cols-10">
      <input
        v-model="input"
        class="w-20 rounded border-2 border-slate-300 bg-inherit px-1 uppercase transition-all dark:border-slate-700"
        aria-label="Input a HEX color"
        @change="colorToPosition(input)"
      />
      <button
        class="col-start-6 grid-flow-row-dense rounded px-1 transition-all hover:text-blue-600 focus:text-blue-600"
        @click="update('currentColor')"
      >
        RESET
      </button>
      <button
        class="col-start-9 col-end-11 flex items-center justify-center rounded border-2 border-slate-300 transition-all hover:text-[--feature-color] focus:text-[--feature-color] dark:border-slate-700"
        @click="update(input)"
      >
        OK
      </button>
    </div>
  </div>
</template>

<style scoped>
#shade,
#hue {
  box-shadow:
    0 0 0 0.05rem rgb(51 65 85),
    0 0 0.05rem 0.05rem currentColor;
}

#shadeCursor,
#hueCursor {
  box-shadow:
    0 0 0 0.1rem white,
    inset 0 0 0.1rem 0.1rem #0006,
    0 0 0.1rem 0.1rem #0006;
}
</style>

// src/popup/components/ColorPicker.tsx
import { Popover, Transition } from '@headlessui/react';
import { Icon } from '@iconify/react';
import React, { Fragment, useEffect, useState } from 'react';
import tinycolor from 'tinycolor2';

interface ColorPickerProps {
  color: string;
  onChange: (color: string) => void;
}

export default function ColorPicker({ color, onChange }: ColorPickerProps) {
  return (
    <Popover className="flex grow">
      {({ open }) => (
        <>
          <Popover.Button className="group flex flex-1 items-center justify-between rounded px-2 capitalize transition-all hover:bg-gray-200 focus-visible:bg-gray-200 dark:hover:bg-slate-700 dark:focus-visible:bg-slate-700">
            Select color
            <div
              className="hidden size-3 rounded-full group-hover:block group-focus-visible:block"
              style={{ backgroundColor: color }}
            />
          </Popover.Button>
          <Transition
            appear
            show={open}
            as={Fragment}
            enter="transition ease-out duration-300"
            enterFrom="opacity-0 scale-95"
            enterTo="opacity-100 scale-100"
            leave="transition ease-in duration-200"
            leaveFrom="opacity-100 scale-100"
            leaveTo="opacity-0 scale-95"
          >
            <Popover.Panel focus className="absolute inset-0 z-50 bg-white dark:bg-slate-900">
              <ColorPickerPanel color={color} onChange={onChange}>
                <Popover.Button className="flex items-center justify-center gap-2 rounded border-none px-1.5 font-sans shadow-sm outline-none ring-1 ring-gray-300 transition-all hover:text-primary focus-visible:text-primary focus-visible:ring-2 focus-visible:ring-primary dark:ring-slate-700 dark:focus-visible:ring-primary">
                  Close Picker Panel
                  <Icon
                    className="size-4"
                    aria-hidden="true"
                    icon="line-md:circle-to-confirm-circle-transition"
                  />
                </Popover.Button>
              </ColorPickerPanel>
            </Popover.Panel>
          </Transition>
        </>
      )}
    </Popover>
  );
}

interface ColorPickerPanelProps {
  color: string;
  children: React.ReactNode;
  onChange: (color: string) => void;
}

function ColorPickerPanel({ color, children, onChange }: ColorPickerPanelProps) {
  const [input, setInput] = useState(tinycolor(color).toHexString());
  const presetColors = [
    'black',
    'white',
    'violet',
    'orange',
    'gold',
    'sienna',
    'lime',
    'springgreen',
    'forestgreen',
    'fuchsia',
    'blueviolet',
    'orangered',
    'aquamarine',
    'teal',
    'royalblue',
    'darkturquoise',
    'silver',
    'crimson',
    'pink',
    'lightskyblue',
    'aqua',
    'lightsalmon',
    'paleturquoise',
    'gray',
    'tomato',
  ];
  useEffect(() => {
    setInput(tinycolor(color).toHexString());
  }, [color]);

  function clamp(value: number, min: number, max: number): number {
    return Math.min(Math.max(value, min), max);
  }

  function handleSaturationCanvasPointerDown(event: React.PointerEvent<HTMLDivElement>) {
    const saturationCanvas = event.currentTarget;
    const { width, height, left, top } = saturationCanvas.getBoundingClientRect();
    onChange(
      tinycolor({
        h: tinycolor(color).toHsv().h,
        s: clamp((event.clientX - left) / width, 0, 1),
        v: clamp(1 - (event.clientY - top) / height, 0, 1),
      }).toHexString(),
    );
    saturationCanvas.setPointerCapture(event.pointerId);
    saturationCanvas.addEventListener('pointermove', handlePointerMove);
    saturationCanvas.addEventListener('pointerup', handlePointerUp);

    function handlePointerMove(event: PointerEvent) {
      onChange(
        tinycolor({
          h: tinycolor(color).toHsv().h,
          s: clamp((event.clientX - left) / width, 0, 1),
          v: clamp(1 - (event.clientY - top) / height, 0, 1),
        }).toHexString(),
      );
    }
    function handlePointerUp() {
      saturationCanvas.releasePointerCapture(event.pointerId);
      saturationCanvas.removeEventListener('pointermove', handlePointerMove);
      saturationCanvas.removeEventListener('pointerup', handlePointerUp);
    }
  }

  function handleHueCanvasPointerDown(event: React.PointerEvent<HTMLDivElement>) {
    const hueCanvas = event.currentTarget;
    const { width, left } = hueCanvas.getBoundingClientRect();
    onChange(
      tinycolor({
        h: clamp(((event.clientX - left) / width) * 360, 0, 359),
        s: tinycolor(color).toHsv().s,
        v: tinycolor(color).toHsv().v,
      }).toHexString(),
    );
    hueCanvas.setPointerCapture(event.pointerId);
    hueCanvas.addEventListener('pointermove', handlePointerMove);
    hueCanvas.addEventListener('pointerup', handlePointerUp);
    function handlePointerMove(event: PointerEvent) {
      onChange(
        tinycolor({
          h: clamp(((event.clientX - left) / width) * 360, 0, 359),
          s: tinycolor(color).toHsv().s,
          v: tinycolor(color).toHsv().v,
        }).toHexString(),
      );
    }
    function handlePointerUp() {
      hueCanvas.releasePointerCapture(event.pointerId);
      hueCanvas.removeEventListener('pointermove', handlePointerMove);
      hueCanvas.removeEventListener('pointerup', handlePointerUp);
    }
  }
  return (
    <div className="flex size-full flex-col justify-between px-2.5 py-3">
      <div className="relative aspect-[4/3] w-full cursor-crosshair rounded-sm">
        <div
          onPointerDown={handleSaturationCanvasPointerDown}
          className="absolute inset-0 rounded-sm shadow-inner"
          style={{
            background: `linear-gradient(to right, white, ${tinycolor({
              h: tinycolor(color).toHsv().h,
              s: 100,
              v: 100,
            }).toHexString()})`,
          }}
        >
          <div className="absolute inset-0 rounded-sm bg-gradient-to-b from-transparent to-black" />
          {/* Saturation and value picker */}
          <div
            className="absolute size-1 -translate-x-1/2 -translate-y-1/2 rounded-full "
            style={{
              boxShadow:
                'rgb(255, 255, 255) 0px 0px 0px 1.5px, rgba(0, 0, 0, 0.3) 0px 0px 1px 1px inset, rgba(0, 0, 0, 0.4) 0px 0px 1px 2px',
              left: `${tinycolor(color).toHsv().s * 100}%`,
              top: `${100 - tinycolor(color).toHsv().v * 100}%`,
            }}
          />
        </div>
      </div>
      <div className="flex gap-1">
        <div
          onPointerDown={handleHueCanvasPointerDown}
          className="relative h-4 flex-1 cursor-crosshair rounded-sm"
          style={{
            background:
              'linear-gradient(to right, rgb(255, 0, 0) 0%, rgb(255, 255, 0) 17%, rgb(0, 255, 0) 33%, rgb(0, 255, 255) 50%, rgb(0, 0, 255) 67%, rgb(255, 0, 255) 83%, rgb(255, 0, 0) 100%)',
          }}
        >
          {/* Hue picker */}
          <div
            className="absolute top-1/2 h-3.5 w-1 -translate-x-1/2 -translate-y-1/2 rounded-[1px] bg-white "
            style={{
              boxShadow: 'rgba(0, 0, 0, 0.6) 0px 0px 2px',
              left: `${(tinycolor(color).toHsv().h / 360) * 100}%`,
            }}
          />
        </div>
        <div
          className="size-4 rounded-sm"
          style={{
            boxShadow:
              'rgba(0, 0, 0, 0.15) 0px 0px 0px 1px inset, rgba(0, 0, 0, 0.25) 0px 0px 4px inset',
            backgroundColor: color,
          }}
        />
      </div>
      <div>
        <div className="flex items-center justify-between text-sm">
          <label>
            <span>HEX </span>
            <input
              className="h-6 w-[5rem] rounded border-none px-1.5 font-mono text-sm uppercase shadow-sm ring-1 ring-inset ring-gray-300 focus:border-none focus:ring-2 focus:ring-primary dark:bg-slate-950 dark:ring-slate-700 dark:focus-visible:ring-primary"
              value={input}
              onChange={(event) => {
                setInput(event.target.value);
              }}
              onKeyDown={(event) => {
                if (event.key === 'Enter' && tinycolor(input).isValid()) {
                  onChange(input);
                }
              }}
            />
          </label>
          <button
            className="flex h-6 items-center justify-center gap-0.5 rounded border-none px-1.5 font-sans shadow-sm outline-none ring-1 ring-gray-300 transition-all hover:text-primary focus-visible:text-primary focus-visible:ring-2 focus-visible:ring-primary dark:bg-slate-950 dark:ring-slate-700 dark:focus-visible:ring-primary"
            onClick={() => {
              onChange('currentColor');
            }}
          >
            Reset
            <Icon className="text-lg" aria-hidden="true" icon="material-symbols:refresh-rounded" />
          </button>
        </div>
      </div>
      <div className="grid grid-cols-5 grid-rows-5 gap-2.5 border-t-2 border-gray-300 pt-3 dark:border-slate-700">
        {presetColors.map((color) => {
          const baseShadow = 'rgba(0, 0, 0, 0.15) 0px 0px 0px 1px inset';
          const focusShadow = `${baseShadow} ,${color} 0px 0px 6px`;
          return (
            <button
              key={color}
              className="h-4 w-8 cursor-pointer rounded-sm outline-none"
              style={{
                boxShadow: baseShadow,
                backgroundColor: color,
              }}
              onFocus={(event) => {
                event.currentTarget.style.boxShadow = focusShadow;
              }}
              onBlur={(event) => {
                event.currentTarget.style.boxShadow = baseShadow;
              }}
              onClick={() => {
                onChange(color);
              }}
            >
              <span className="sr-only">{color}</span>
            </button>
          );
        })}
      </div>
      {children}
    </div>
  );
}
