// src/popup/components/Link.tsx
import { Icon } from "@iconify/react";

import ToolTip from "./ToolTip";

interface LinkProps {
  href: string;
  text: string;
  tip?: string;
}

export default function Link({ href, text, tip }: LinkProps) {
  function InlineLink() {
    return (
      <a
        target="_blank"
        href={href}
        rel="noopener noreferrer"
        className="flex flex-1 items-center gap-x-1 rounded px-2 capitalize transition duration-300 hover:bg-gray-200 hover:text-primary focus-visible:bg-gray-200 focus-visible:text-primary dark:hover:bg-slate-700 dark:focus-visible:bg-slate-700"
      >
        {text}
        <Icon aria-hidden="true" icon="ci:link" />
      </a>
    );
  }
  return tip ? (
    <ToolTip tip={tip}>
      <InlineLink />
    </ToolTip>
  ) : (
    <InlineLink />
  );
}

// src/popup/components/Link.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'

const props = defineProps<{
  link: string
}>()
</script>

<template>
  <a target="_blank" :href="props.link" class="link">
    <slot name="default" />
    <Icon icon="ci:link" aria-hidden="true" />
  </a>
</template>

<style scoped>
.link {
  appearance: none;
  cursor: pointer;
  color: currentColor;
  text-decoration: none;
  height: 1.5rem;
  padding: 0 0.5rem;
  border-radius: 0.3rem;
  display: flex;
  align-items: center;
  transition: color 500ms ease-in-out;
  gap: 0.3rem;
}

.link:focus,
.link:hover {
  color: var(--feature);
}
</style>
