// src/popup/components/Select.tsx
import { Listbox, Transition } from '@headlessui/react';
import { Icon } from '@iconify/react';
import { Fragment } from 'react';

interface SelectProps {
  label: string;
  selected: string;
  options: string[];
  onChange: (selected: string) => void;
}

export default function Select({ label, selected, options, onChange }: SelectProps) {
  return (
    <Listbox value={selected} onChange={onChange}>
      <div className="relative w-full">
        <Listbox.Label className="sr-only">{label}</Listbox.Label>
        <Listbox.Button className="group peer flex w-full items-center justify-between rounded px-2 capitalize transition-all hover:bg-gray-200 focus-visible:bg-gray-200 ui-open:bg-gray-200 dark:hover:bg-slate-700 dark:focus-visible:bg-slate-700 dark:ui-open:bg-slate-700">
          {selected}
          <Icon
            className="hidden group-hover:flex group-focus-visible:flex ui-open:flex"
            aria-hidden="true"
            icon="ep:arrow-down-bold"
          />
        </Listbox.Button>
        <Transition
          enter="transition duration-100 ease-out"
          enterFrom="transform scale-95 opacity-0"
          enterTo="transform scale-100 opacity-100"
          leave="transition duration-75 ease-out"
          leaveFrom="transform scale-100 opacity-100"
          leaveTo="transform scale-95 opacity-0"
          as={Fragment}
        >
          <Listbox.Options className="absolute left-0 z-50 mt-1 flex w-full flex-col rounded-md border-2 border-gray-300 bg-white py-1 shadow dark:border-slate-700 dark:bg-slate-900">
            {options.map((item) => (
              <Listbox.Option key={item} value={item} as={Fragment}>
                {({ active, selected }) => (
                  <li
                    className={`${active ? 'text-primary' : 'text-current'}
                    ${selected ? 'text-primary' : ''}
                    box-content flex cursor-pointer items-center justify-between px-[6px] capitalize transition-all hover:bg-gray-200 focus:z-10 focus:bg-gray-200 ui-active:bg-gray-200 dark:hover:bg-slate-700 dark:focus:bg-slate-700 dark:ui-active:bg-slate-700`}
                  >
                    {item}
                    {selected && <Icon aria-hidden="true" icon="ep:select" />}
                  </li>
                )}
              </Listbox.Option>
            ))}
          </Listbox.Options>
        </Transition>
      </div>
    </Listbox>
  );
}

// src/popup/components/Select.vue
<script setup lang="ts">
import { useFocusWithin } from '@vueuse/core'
import { ref, watch } from 'vue'

import DownIcon from 'data-text:@Icons/Down.svg'

const props = defineProps<{
  options: string[]
  modelValue: string
}>()

const emit = defineEmits<{
  'update:modelValue': [modelValue: string]
  change: []
}>()

const display = ref(false)
const changeOption = (option: string) => {
  display.value = false
  emit('update:modelValue', option)
  emit('change')
}

const select = ref<HTMLElement | null>(null)
const { focused } = useFocusWithin(select)
watch(focused, () => {
  display.value = false
})
</script>

<template>
  <button
    class="select"
    ref="select"
    :class="{ display: display }"
    @click.self="display = !display"
  >
    {{ props.modelValue }}
    <div v-html="DownIcon" class="selectIcon" />
    <Transition>
      <div class="panel" v-if="display">
        <button
          class="option"
          v-for="option of props.options"
          :class="{ selected: option === props.modelValue }"
          @click="changeOption(option)"
        >
          {{ option }}
        </button>
      </div>
    </Transition>
  </button>
</template>

<style scoped>
button {
  background-color: transparent;
  border: none;
  color: currentColor;
  width: 100%;
  cursor: pointer;
  text-transform: capitalize;
}

.select {
  position: relative;
  cursor: pointer;
  height: 1.5rem;
  padding: 0 0.5rem;
  border-radius: 0.3rem;
  display: flex;
  align-items: center;
  flex-grow: 1;
  justify-content: space-between;
  transition: opacity 250ms ease-in-out;
}

.display {
  background-color: var(--hover);
}

.selectIcon {
  display: none;
}

.selectIcon :deep(svg) {
  color: var(--feature);
  width: 1rem;
  height: auto;
}

.select:focus-within .selectIcon,
.select:hover .selectIcon {
  display: flex;
  align-items: center;
}

.panel {
  width: 100%;
  display: flex;
  flex-direction: column;
  position: absolute;
  top: 1.5rem;
  left: 0;
  z-index: 1;
  box-shadow: 0 0 1rem var(--hover);
  border-radius: 0.4rem;
  background-color: var(--background);
  border: 0.1rem solid var(--feature);
}

.selected {
  background-color: var(--hover);
  color: var(--feature);
}

.option {
  display: flex;
  align-items: center;
  padding: 0 0.5rem;
  box-sizing: border-box;
  height: 1.5rem;
  text-align: left;
  transition: background-color 250ms ease-in-out;
}

.option:focus,
.option:hover {
  background-color: var(--hover);
}

.option:focus {
  z-index: 1;
}

.option:first-child {
  border-radius: 0.3rem 0.3rem 0 0;
}

.option:last-child {
  border-radius: 0 0 0.3rem 0.3rem;
}

.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
