// entrypoints/popup/components/Select.tsx
import {
  Listbox,
  ListboxButton,
  ListboxOption,
  ListboxOptions,
  Transition,
} from "@headlessui/react";

import ToolTip from "./ToolTip";

interface SelectProps {
  selected: string;
  options: { label: string; value: string }[];
  tip?: string;
  onChange: (selected: string) => void;
}

export default function Select({ selected, options, tip, onChange }: SelectProps) {
  function ListBoxButton() {
    return (
      <ListboxButton className="group peer flex w-full items-center justify-between rounded px-2 capitalize transition-all dark:focus-visible:bg-slate-700 dark:hover:bg-slate-700 dark:ui-open:bg-slate-700 focus-visible:bg-gray-200 hover:bg-gray-200 ui-open:bg-gray-200">
        {options.find((option) => option.value === selected)?.label}
        <i className="i-tabler-chevron-down hidden group-focus-visible:flex group-hover:flex ui-open:flex" />
      </ListboxButton>
    );
  }

  return (
    <Listbox value={selected} onChange={onChange}>
      <div className="relative w-full">
        {tip ? (
          <ToolTip tip={tip}>
            <ListBoxButton />
          </ToolTip>
        ) : (
          <ListBoxButton />
        )}
        <Transition
          enter="transition duration-100 ease-out"
          enterFrom="transform scale-95 opacity-0"
          enterTo="transform scale-100 opacity-100"
          leave="transition duration-75 ease-out"
          leaveFrom="transform scale-100 opacity-100"
          leaveTo="transform scale-95 opacity-0"
        >
          <ListboxOptions
            as="div"
            anchor="bottom"
            className="z-40 mt-1 flex w-[var(--button-width)] flex-col rounded-md border-2 border-gray-300 bg-white py-1 shadow dark:border-slate-700 dark:bg-slate-900"
          >
            {options.map((item) => (
              <ListboxOption key={item.value} value={item.value}>
                {({ focus, selected }) => (
                  <li
                    className={`${focus ? "text-sky-500" : "text-current"}${selected ? "text-sky-500" : ""}box-content flex cursor-pointer items-center justify-between px-[6px] capitalize transition-all focus:z-10 dark:focus:bg-slate-700 dark:hover:bg-slate-700 dark:ui-active:bg-slate-700 focus:bg-gray-200 hover:bg-gray-200 ui-active:bg-gray-200`}
                  >
                    {item.label}
                    {selected && <i className="i-tabler-check" />}
                  </li>
                )}
              </ListboxOption>
            ))}
          </ListboxOptions>
        </Transition>
      </div>
    </Listbox>
  );
}

// src/popup/components/Select.vue
<script setup lang="ts">
import { useFocusWithin } from '@vueuse/core'
import { ref, watch } from 'vue'

import DownIcon from 'data-text:@Icons/Down.svg'

const props = defineProps<{
  options: string[]
  modelValue: string
}>()

const emit = defineEmits<{
  'update:modelValue': [modelValue: string]
  change: []
}>()

const display = ref(false)
const changeOption = (option: string) => {
  display.value = false
  emit('update:modelValue', option)
  emit('change')
}

const select = ref<HTMLElement | null>(null)
const { focused } = useFocusWithin(select)
watch(focused, () => {
  display.value = false
})
</script>

<template>
  <button
    class="select"
    ref="select"
    :class="{ display: display }"
    @click.self="display = !display"
  >
    {{ props.modelValue }}
    <div v-html="DownIcon" class="selectIcon" />
    <Transition>
      <div class="panel" v-if="display">
        <button
          class="option"
          v-for="option of props.options"
          :class="{ selected: option === props.modelValue }"
          @click="changeOption(option)"
        >
          {{ option }}
        </button>
      </div>
    </Transition>
  </button>
</template>

<style scoped>
button {
  background-color: transparent;
  border: none;
  color: currentColor;
  width: 100%;
  cursor: pointer;
  text-transform: capitalize;
}

.select {
  position: relative;
  cursor: pointer;
  height: 1.5rem;
  padding: 0 0.5rem;
  border-radius: 0.3rem;
  display: flex;
  align-items: center;
  flex-grow: 1;
  justify-content: space-between;
  transition: opacity 250ms ease-in-out;
}

.display {
  background-color: var(--hover);
}

.selectIcon {
  display: none;
}

.selectIcon :deep(svg) {
  color: var(--feature);
  width: 1rem;
  height: auto;
}

.select:focus-within .selectIcon,
.select:hover .selectIcon {
  display: flex;
  align-items: center;
}

.panel {
  width: 100%;
  display: flex;
  flex-direction: column;
  position: absolute;
  top: 1.5rem;
  left: 0;
  z-index: 1;
  box-shadow: 0 0 1rem var(--hover);
  border-radius: 0.4rem;
  background-color: var(--background);
  border: 0.1rem solid var(--feature);
}

.selected {
  background-color: var(--hover);
  color: var(--feature);
}

.option {
  display: flex;
  align-items: center;
  padding: 0 0.5rem;
  box-sizing: border-box;
  height: 1.5rem;
  text-align: left;
  transition: background-color 250ms ease-in-out;
}

.option:focus,
.option:hover {
  background-color: var(--hover);
}

.option:focus {
  z-index: 1;
}

.option:first-child {
  border-radius: 0.3rem 0.3rem 0 0;
}

.option:last-child {
  border-radius: 0 0 0.3rem 0.3rem;
}

.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
